name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Install Deps
        run: sudo apt-get install -y binutils musl-tools
      - name: Checkout
        uses: actions/checkout@v2

     
      - name: test strip
        run: which strip && strip --help

